CREATE TABLE [User]
(
    UserID INT PRIMARY KEY IDENTITY(1,1),
    UserName NVARCHAR(100) NOT NULL,
    [Password] NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MobileNo NVARCHAR(100) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    Created DATETIME DEFAULT GETDATE(),
    Modified DATETIME NOT NULL
);


CREATE TABLE Department
(
	DepartmentID INT PRIMARY KEY IDENTITY(1,1),
	DepartmentName NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(100),
	IsActive BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Modified DATETIME NOT NULL,
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID)
);

CREATE TABLE Doctor
(
	DoctorID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(20) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Qualification NVARCHAR(100) NOT NULL,
	Specialization NVARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Modified DATETIME NOT NULL,
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID)
);

CREATE TABLE DoctorDepartment
(
	DoctorDepartmentID INT PRIMARY KEY IDENTITY(1,1),
	DoctorID INT NOT NULL FOREIGN KEY REFERENCES Doctor(DoctorID),
	DepartmentID INT NOT NULL FOREIGN KEY REFERENCES Department(DepartmentID),
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Modified DATETIME NOT NULL,
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID)
);

CREATE TABLE Patient
(
	PatientID INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	DateOfBirth DATETIME NOT NULL,
	Gender NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(100) NOT NULL,
	City NVARCHAR(100) NOT NULL,
	[State] NVARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Modified DATETIME NOT NULL,
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID)
);

CREATE TABLE Appointment
(
	AppointmentID INT PRIMARY KEY IDENTITY(1,1),
	DoctorID INT FOREIGN KEY REFERENCES Doctor(DoctorID),
	PatientID INT FOREIGN KEY REFERENCES Patient(PatientID),
	AppointmentDate DATETIME NOT NULL,
	AppointmentStatus NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(100) NOT NULL,
	SpecialRemarks NVARCHAR(100) NOT NULL,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	Modified DATETIME NOT NULL,
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](UserID),
	TotalConsultedAmount DECIMAL(5,2) NULL
);